apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: create-customer-details-rest
spec:
  replicas: 1
  pod:
    containers:
      runtime:
        image: test to see if gets replace
