kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: custom-apic-config-pipeline
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: apic-pipelines-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: custom-apic-config-pipeline